### ISSUE TITLE
Questions on Python3 Version

### ISSUE THREAD

**Issue by blangero** [cz7asm/pyStarDictViewer#1]
Hi Cz7asm,

Thanks a lot for your great work, this project is really helpful!

 I don't mean to be offensive, but is it possible that this project supports both Python ver 2 and ver 3?

Also, is there any further planning for this project?

Thanks and regards,
Blangero

**Comment by cz7asm** [comment]
Hi,
Firt of all I'm sorry to notice this question so late, I somehow missed the notification.
I will have a look when time allows, it would be very useful indeed. I can see you already did something. Again, sorry for such a late reply.

**Comment by blangero** [comment]
Great, and thank you for your info!

**Comment by blangero** [comment]
Checking the question created 2 years before, I'm really embarrassed for creating it - it provides no help to the function of the tool but only to make it easier consumed. 
I would have to say that I didn't stick to this solution as the requirement dropped, so don't put more effort on it only for I'm asking it - you've got other good repos to maintain which will be benifitial to more guys!
